App:menu.c add_fist.o add_last.o add_sort.o delete_first.o delete_last.o Display.o delete_data.o delete_last_nth.o reverse.o
	gcc -g menu.c add_fist.o add_last.o add_sort.o delete_first.o delete_last.o Display.o delete_data.o delete_last_nth.o reverse.o -o App
